<?php

namespace Controller;

use Core\Config;
use Model\DiaryModel;
use Model\UsersModel;
use TexLab\MyDB\DB;
use TexLab\MyDB\DbEntity;
use View\View;

class DiaryController extends AbstractTableController
{

    protected $tableName = "diary";
    protected $usersTable;

    public function __construct(View $view)
    {
        parent::__construct($view);
        $this->table = new DiaryModel(
            $this->tableName,
            DB::Link([
                'host' => Config::MYSQL_HOST,
                'username' => Config::MYSQL_USER_NAME,
                'password' => Config::MYSQL_PASSWORD,
                'dbname' => Config::MYSQL_DATABASE
            ])
        );

        $this->usersTable = new UsersModel(
            "users",
            DB::Link([
                'host' => Config::MYSQL_HOST,
                'username' => Config::MYSQL_USER_NAME,
                'password' => Config::MYSQL_PASSWORD,
                'dbname' => Config::MYSQL_DATABASE
            ])
        );
    }

    public function actionShow(array $data)
    {
        parent::actionShow($data);
        $this
            ->view
            ->setFolder('diary');


        //        $this->usersTable->getUsers();

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
                'table' => $this
                    ->table
                    ->reset()
                    ->setPageSize(Config::PAGE_SIZE)
                    ->getApplicationPage($data['get']['page'] ?? 1)
            ]
        );
    }

    public function actionShowEdit(array $data)
    {
        parent::actionShowEdit($data); // TODO: Change the autogenerated stub

        $this
            ->view
            ->setFolder('diary');

        $this->view->addData(
            [
                "usersList" => $this->usersTable->getUsers(),
            ]
        );
    }
}
