<?php

namespace Controller;

class TrainingdiaryController extends AbstractTableController
{

    protected $tableName = "trainingdiary";
    // public function __construct(View $view)
    // {
    //     parent::__construct($view);
    //     $this->view->setFolder('products');
    // }

    // public function actionAdd(array $data)
    // {
    //     $data['post']['image'] = $_FILES['image']['name'];
    //     $ext = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
    //     $id = $this->table->add($data['post']);
    //     move_uploaded_file($_FILES['image']['tmp_name'], "images/products/$id.$ext");

    //     $this->redirect('?action=show&type=' . $this->getClassName());
    // }

    // public function actionEdit(array $data)
    // {
    //     $data['post']['image'] = $_FILES['image']['name'];
    //     $ext = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
    //     $id = $data['post']['id'];
    //     move_uploaded_file($_FILES['image']['tmp_name'], "images/products/$id.$ext");
    //     parent::actionEdit($data); // TODO: Change the autogenerated stub
    // }

    // public function actionDel(array $data)
    // {
    //     $id = $data['get']['id'];
    //     $image = $this->table->get(['id' => $id])[0]['image'];
    //     $ext = pathinfo($image, PATHINFO_EXTENSION);
    //     unlink("images/products/$id.$ext");
    //     parent::actionDel($data); // TODO: Change the autogenerated stub
    // }
}

